name: gold
description: "Gold App For Show Gold Price"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  flutter_bloc: ^9.1.1
  easy_localization: ^3.0.7+1
  dio: ^5.8.0+1
  hive_flutter: ^1.1.0
  cached_network_image_plus:
    git: https://github.com/melshenawyarabapps/cached_network_image_plus.git
  flutter_screenutil: ^5.9.3
  google_mobile_ads: ^6.0.0
  firebase_core: ^3.15.1
  flutter_local_notifications: ^19.3.0
  firebase_messaging: ^15.2.9
  equatable: ^2.0.7
  flutter_native_splash: ^2.4.6
  flutter_hooks: ^0.21.2
  intl: ^0.19.0
  dartz: ^0.10.1
  url_launcher: ^6.3.2
  share_plus: ^11.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  assets:
    - path: assets/dev/
      flavors:
        - dev
    - path: assets/sa/
      flavors:
        - sa
    - assets/
    - assets/test/
    - assets/icons/
    - assets/images/
    - assets/translations/

