name: greenhub
description: "Gold App For Show Gold Price"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  flutter_bloc: ^9.1.1
  easy_localization: ^3.0.7+1
  dio: ^5.8.0+1
  hive_flutter: ^1.1.0
  flutter_screenutil: ^5.9.3
  firebase_core: ^3.15.1
  flutter_local_notifications: ^19.3.0
  firebase_messaging: ^15.2.9
  equatable: ^2.0.7
  flutter_hooks: ^0.21.2
  dartz: ^0.10.1
  collection: ^1.19.1
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.3
  google_fonts: ^6.3.3
  pinput: 6.0.1
  carousel_slider: ^5.1.1
  easy_stepper: ^1.0.1
  image_picker: ^1.1.2
  flutter_secure_storage: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  local_auth: ^3.0.0
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/svgs/
    - assets/images/

